export const POPULAR_MOVIES = "POPULAR_MOVIES";
export const TOP_RATED_MOVIES = "TOP_RATED_MOVIES";
export const UPCOMING_MOVIES = "UPCOMING_MOVIES";
export const IN_THEATERS_MOVIES = "IN_THEATERS_MOVIES";
export const MOVIE_DETAILS = "MOVIE_DETAILS";
export const MOVIE_YOUTUBE_VIDEO = "MOVIE_YOUTUBE_VIDEO";
export const MOVIE_CAST = "MOVIE_CAST";
export const MOVIE_REVIEWS = "MOVIE_REVIEWS";
export const RECOMENDED_MOVIES = "RECOMENDED_MOVIES";
export const MOVIE_COLLECTION = "MOVIE_COLLECTION";

export const POPULAR_SERIES = "POPULAR_SERIES";
export const TOP_RATED_SERIES = "TOP_RATED_SERIES";
export const SERIE_DETAILS = "SERIE_DETAILS";
export const SERIE_YOUTUBE_VIDEO = "MOVIE_YOUTUBE_VIDEO";
export const SERIE_CAST = "SERIE_CAST";
export const SERIE_REVIEVS = "SERIE_REVIEVS";
export const RECOMENDED_SERIES = "RECOMENDED_SERIES";

export const POPULAR_PEOPLE = "POPULAR_PEOPLE";
export const PERSON_DETAILS = "PERSON_DETAILS";
export const PERSON_ACTING_HISTORY = "PERSON_ACTING_HISTORY";

export const SPINNER_LOADING_START = "SPINNER_LOADING_START";
export const SPINNER_LOADING_STOP = "SPINNER_LOADING_STOP";

export const RANDOM_FOOTER_BACKGROUND = "RANDOM_FOOTER_BACKGROUND";

export const MOVIE_SEARCH = "MOVIE_SEARCH";
export const MOVIE_COLLECTIONS = "MOVIE_COLLECTIONS";
export const SERIE_SEARCH = "SERIE_SEARCH";
export const PEOPLE_SEARCH = "PEOPLE_SEARCH";

export const AUTH_START = "AUTH_START";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SINGUP_SUCCESS";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const REDIRECT = "REDIRECT";
export const LOG_OUT = "LOG_OUT";

export const SEND_DATA_SUCCESS = "SEND_DATA_SUCCESS";
export const SEND_DATA_START = "SEND_DATA_START";
export const GET_USER_FAVORITE = "GET_USER_FAVORITE";
export const GET_USER_FINISH = "GET_USER_FINISH";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const CLEAR_USERS_FAV_WA = "CLAER_USERS_FAV_WA";
